// This is the common file. Not naming it common to avoid confusion with the
// built-in common.

NAME: (NAME_PART | PUNCTUATION | " ")+

// Any non-whitespace sequence
NAME_PART: /\S+/
PUNCTUATION: /[.,]/

// Version of newline that doesn't get its own token in the tree. Make its name
// shorter while we're at it
_N: NEWLINE

score: NAME " scores!" (_N use_free_refill)?
use_free_refill: NAME " used their Free Refill." _N NAME " Refills the In!"

%import common.NEWLINE